### PR TITLE
Colorize text output

### PR DESCRIPTION
**Pull request by jcollado**
Use ANSI escape sequences to colorize output in text formatters.

### CODE REVIEW

**Comment by andrew-morris** [comment]
@jcollado couple quick requests-

1. If a device is malicious (in context/gnql txt), can the word `malicious` be RED, `unknown` be grey, and `benign` be green?
2. If a noise is NOT noise in noise quick output, can the IP be grey, if it is noise, can the IP be yellow?

**Comment by jcollado** [comment]
@andrew-morris Sure, let me look into it.

**Comment by jcollado** [comment]
@andrew-morris Updated as requested

**Comment by andrew-morris** [comment]
PERFECT

**Pull request merged**
