### PR TITLE
CLI functionality

### PR DESCRIPTION
**Pull request by jcollado**
Refactor the CLI functionality and make it work using the API client instead of using the `requests` library directly.

This implementation has the following limitations:
- Endpoints not supported by the api client (GNQL) are not supported in the CLI either.
- Supported output formats: json and xml (no text version)

This is an initial PR that will be followed by others that not only add functionality as it is supported by the API client, but also add test cases and documentation.

### CODE REVIEW

**Comment by andrew-morris** [comment]
I'm getting an error when trying to invoke the cli on this latest commit after running `python3 setup.py install`

```$ greynoise
Traceback (most recent call last):
  File "/usr/local/bin/greynoise", line 11, in <module>
    load_entry_point('greynoise==0.1.5', 'console_scripts', 'greynoise')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/greynoise-0.1.5-py3.7.egg/greynoise/cli/__init__.py", line 7, in <module>
    from click_default_group import DefaultGroup
ModuleNotFoundError: No module named 'click_default_group'```

**Comment by jcollado** [comment]
> I'm getting an error when trying to invoke the cli on this latest commit after running `python3 setup.py install`

@andrew-morris That package was missing from `INSTALL_REQUIRES` in `setup.py`. Please try again and let me know if that works.

Anyway, I'll update the documentation to explain how to setup the environment. Ideally the installation in a virtualenv should be something like `pip install -r requirements/common.txt -e .`

**Comment by andrew-morris** [comment]
@jcollado awesome. this is fantastic. 

Can you update so that txt format is default instead of json for gnql please? Otherwise, this is perfect!

**Comment by jcollado** [comment]
Merging this PR since the default output format has been updated to `txt` and there doesn't seem to be any other issue to address.

**Pull request merged**
